Don't restart server within script. Docker servers should be set up to handle this

diff --git a/scripts/start b/scripts/start
--- a/scripts/start
+++ b/scripts/start
@@ -49,14 +49,10 @@ EOD
 fi
 
 # Start server
-while true
-do
-  if [ -x ${target}/server_launcher ]
-  then
-    ${target}/server_launcher
-  else
-    echo "ERROR: ${target}/server_launcher not found or not executable"
-    exit 1
-  fi
-  sleep 1
-done
+if [ -x ${target}/server_launcher ]
+then
+  ${target}/server_launcher
+else
+  echo "ERROR: ${target}/server_launcher not found or not executable"
+  exit 1
+fi
